#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)

# https://help.github.com/en/articles/adding-a-jekyll-theme-to-your-github-pages-site

#markdown: kramdown

theme: jekyll-theme-cayman
#theme: minima

title: Data Analytics & Science
description: Advanced analytics for data-driven decisions
#footer: Krzysztof Satola: [LinkedIn Profile](https://www.linkedin.com/in/ksatola/) or [github repositories](https://github.com/ksatola)